"""Small raw churn witnesses for the full-report B-row judging rules.

The three witnesses are generated by the gate's small fixture path.  Their
6 ordinary, 2 init-failure, 2 burst copies have the same full-run boundary
distribution (close 12, expire 24, prune 36, recent 10) as run7g, without
rerunning its 47-minute measurement.
"""

import copy
import importlib.util
from collections import Counter
from pathlib import Path

import pytest


GATE_PATH = Path(__file__).resolve().parents[1] / "scripts" / "d7_ledger_measure_gate.py"
spec = importlib.util.spec_from_file_location("d7_fullscale_rows_gate", GATE_PATH)
gate = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gate)

SMALL = dict(limit=128, churn_minutes=25, churn_stride_minutes=60,
             fixture_detail_divisor=256)


@pytest.fixture(scope="module")
def witnesses():
    return {
        "ordinary": gate.run_churn_fixture("churn_most_finished_short_ascii", **SMALL),
        "init": gate.run_churn_fixture("churn_init_failed_most_finished_unicode128", **SMALL),
        "burst": gate.run_churn_fixture("churn_burst_ascii128", **SMALL),
    }


def _unit(witnesses, row, *kinds):
    fixtures = [copy.deepcopy(witnesses[kind]) for kind in kinds]
    for fixture in fixtures:
        for cp in fixture["checkpoints"]:
            cp["kind"] = {"tail_before": "tail_80640",
                          "tail_after": "tail_80641"}.get(cp["kind"], cp["kind"])
    scale = ({"burst_details": 8, "normal_calls": 201} if row == "B03" else
             {"hours": 25, "pre_prune_hours": 3} if row == "B10" else {})
    return {"mode": "predicate_unit", "churn_fixtures": fixtures, "test_scale": scale}


def _full(witnesses):
    # run7g's per-source distribution: 6 normal, 2 init failure, 2 burst.
    fixtures = [copy.deepcopy(witnesses[kind])
                for kind in ("ordinary",) * 6 + ("init",) * 2 + ("burst",) * 2]
    return {"mode": "full", "churn_fixtures": fixtures}


def _pad_b13_checkpoints(report):
    required = {"hour": 168, "day": 7, "tail_80640": 1, "tail_80641": 1,
                "highwater_before": 1, "highwater_after": 1}
    for f in report["churn_fixtures"]:
        cps = f["checkpoints"]
        for cp in cps:
            cp["kind"] = {"tail_before": "tail_80640",
                          "tail_after": "tail_80641"}.get(cp["kind"], cp["kind"])
        counts = Counter(cp["kind"] for cp in cps)
        for kind, minimum in required.items():
            exemplar = next(cp for cp in cps if cp["kind"] == kind)
            for index in range(minimum - counts[kind]):
                extra = copy.deepcopy(exemplar)
                extra["checkpoint_id"] = f"budget-only-{kind}-{index}"
                cps.append(extra)


@pytest.mark.parametrize("row,kinds", [
    ("B03", ("ordinary", "burst")),
    ("B09", ("init",)),
    ("B10", ("burst",)),
    ("B12", ("burst",)),
    ("B14", ("burst",)),
    ("B16", ("init",)),
    ("B18", ("init",)),
])
def test_small_raw_witness_passes_row(witnesses, row, kinds):
    report = _unit(witnesses, row, *kinds)
    result = gate.evaluate_row(row, report, attachments={})
    assert result["status"] == "PASS", result


@pytest.mark.parametrize("row", ["B08", "B09", "B11", "B12", "B13"])
def test_full_boundary_counts_are_across_all_ten_witnesses(witnesses, row):
    report = _full(witnesses)
    if row == "B13":
        _pad_b13_checkpoints(report)
        gate._evaluate_b_rest(row, report)
    else:
        gate._b_followup(row, report, report["churn_fixtures"], False)


@pytest.mark.parametrize("row,kind", [
    ("B08", "probe_close_at"),
    ("B09", "probe_expire_at"),
    ("B11", "probe_prune_at"),
    ("B12", "probe_recent_at"),
    ("B13", "probe_close_at"),
])
def test_full_boundary_total_still_rejects_missing_sample(witnesses, row, kind):
    report = _full(witnesses)
    if row == "B13":
        _pad_b13_checkpoints(report)
    fixture = report["churn_fixtures"][0]
    fixture["checkpoints"].remove(next(cp for cp in fixture["checkpoints"]
                                       if cp["kind"] == kind))
    with pytest.raises((gate._EvidenceMissing, gate._EvidenceViolation)):
        if row == "B13":
            gate._evaluate_b_rest(row, report)
        else:
            gate._b_followup(row, report, report["churn_fixtures"], False)


def test_b10_keeps_pre_schedule_auxiliary_prunes_out_of_normal_hours(witnesses):
    report = _unit(witnesses, "B10", "burst")
    fixture = report["churn_fixtures"][0]
    registers = {event["id"]: event for event in fixture["fixture_provenance"]["api_trace"]
                 if event["action"] == "register"}
    early = [entry for entry in fixture["tomb_due_ledger"] if entry["due_hour"] <= 0]
    assert early and all(registers[entry["id"]]["auxiliary"] for entry in early)
    first_hour = next(cp for cp in fixture["checkpoints"] if cp["kind"] == "hour")
    assert first_hour["pruned_since_previous_hour"] == len(early)
    assert gate.evaluate_row("B10", report, attachments={})["status"] == "PASS"


def test_b10_rejects_non_auxiliary_due_before_first_hour(witnesses):
    report = _unit(witnesses, "B10", "burst")
    fixture = report["churn_fixtures"][0]
    normal_ids = {event["id"] for event in fixture["fixture_provenance"]["api_trace"]
                  if event["action"] == "register" and not event["auxiliary"]}
    entry = next(entry for entry in fixture["tomb_due_ledger"] if entry["id"] in normal_ids)
    entry["due_hour"] = 0
    result = gate.evaluate_row("B10", report, attachments={})
    assert result["status"] == "FAIL"
    assert result["reason"] == "normal tomb due before first hour"


def test_b12_rejects_later_normal_finish_in_same_bucket(witnesses):
    report = _unit(witnesses, "B12", "burst")
    fixture = report["churn_fixtures"][0]
    trace = fixture["fixture_provenance"]["api_trace"]
    normal_ids = {event["id"] for event in trace
                  if event["action"] == "register" and not event["auxiliary"]}
    finishes = [event for event in trace if event["action"] == "finish" and
                event["classification"] == "finalized" and event["id"] in normal_ids]
    first, later = finishes[:2]
    assert first["id"] != later["id"]
    assert first["recent_exit_at"] == later["recent_exit_at"]
    for cp in fixture["checkpoints"]:
        if cp["kind"] in ("probe_recent_before", "probe_recent_at"):
            cp["identity_samples"][0]["id"] = later["id"]
            cp["identity_samples"][0]["registered_seq"] = later["registered_seq"]
    result = gate.evaluate_row("B12", report, attachments={})
    assert result["status"] == "FAIL"
    assert result["reason"] == "recent target is not first normal completion"
